version: '3'

volumes:
  betterff_db:


services:
  backend:
    build: backend
    restart: always
    environment:
      - PORT=${PORT}
      - EXECUTABLE_PATH=/usr/bin/google-chrome
      - DB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - DB_HOST=database
      - DB_PORT=3306
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - database
  database:
    build: db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    expose:
      - 3306
    ports:
      - ${DB_PORT}:3306
    volumes:
      - betterff_db:/var/lib/mysql
