name: Build and deplay the site to the server

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  Deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to Server
        run: |
          cp -R * /home/betterff/dist/
