name: Build and deplay the site to the server

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  Build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Build Static Site
        run: |
          npm install
          npm run migrate
  Deploy:
    runs-on: self-hosted
    # needs: Build
    steps:
      - name: Deploy to Server
        run: |
          cp -R * /home/betterff/dist/
